source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'ZMJImageEditor_Example' do
  pod 'ZMJImageEditor', :path => '../'

  target 'ZMJImageEditor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
